[PIPELINES] Fix fail for running deploys

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -136,6 +136,19 @@ function get_latest_stage_run_status() {
   get_stage_run_history $1 $2 | jq -r .stages[0].jobs[0].state
 }
 
+function fail_if_stage_running() {
+  local pipeline_name=$1
+  local stage_name=$2
+
+  local stage_status=$(get_latest_stage_run_status $pipeline_name $stage_name)
+
+  echo Stage $stage_name in $pipeline_name is $stage_status
+  if [[ "$stage_status" != "Completed" ]]; then
+    echo "Failing e2e tests fast as $pipeline_name is currently running $stage_name"
+    exit 37
+  fi
+  echo Continuing as $pipeline_name $stage_name is not running
+}
 
 ###########
 ## TASKS ##
@@ -260,20 +273,8 @@ case "${command}" in
 
       # make sure all are in state completed at start of run
 
-      # pds-adaptor
-      echo spiked pds-adaptor deploy is $(get_latest_stage_run_status pds-adaptor deploy.dev)
-      if [[  $(get_latest_stage_run_status pds-adaptor deploy.dev) -ne "Completed" ]]; then
-        echo "Failing e2e tests fast as PDS adaptor is currently deploying to dev"
-        exit 37
-      fi
-
-
-      # nems-event-processor
-      echo spiked nems-event-processor deploy is $(get_latest_stage_run_status nems-event-processor deploy.dev)
-      if [[  $(get_latest_stage_run_status nems-event-processor deploy.dev) -ne "Completed" ]]; then
-        echo "Failing e2e tests fast as NEMS event processor is currently deploying to dev"
-        exit 37
-      fi
+      fail_if_stage_running pds-adaptor deploy.dev
+      fail_if_stage_running nems-event-processor deploy.dev
 
       echo No deployments running into dev. Starting e2e tests
 
